[package]
name = "jotoba"
version = "0.1.0"
authors = ["jojii <jojii@gmx.net>"]
edition = "2021"
license = "GPLv3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
japanese = { path = "../lib/japanese" }
search = { path = "../lib/search" }
error = { path = "../lib/error" }
utils = { path = "../lib/utils" }
api = { path = "../lib/api" }
frontend = { path = "../lib/frontend" }
config = { path = "../lib/config" }
localization = { path = "../lib/localization" }
resources = { path = "../lib/resources" }
actix-files = "0.6.0-beta.8"
actix-web = "4.0.0-beta.11"
actix-multipart = "0.4.0-beta.7"
argparse = "0.2.2"
env_logger = "0.9.0"
serde = "1.0.130"
log = "0.4.14"
#sentry-actix = { version = "0.23.0", optional = true }
sentry = { version = "0.23.0", optional = true }

[features]
sentry_error = [ "sentry", "frontend/sentry_error" ]
img_scan = [ "api/img_scan" ]
default = [ "sentry_error", "img_scan" ]
