[package]
name = "jotoba"
version = "0.1.0"
authors = ["jojii <jojii@gmx.net>"]
edition = "2021"
license = "GPLv3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
japanese = { path = "../lib/japanese" }
sentence_reader  = { path = "../lib/sentence_reader" }
search = { path = "../lib/search" }
error = { path = "../lib/error" }
types = {path = "../lib/types"}
utils = { path = "../lib/utils" }
api = { path = "../lib/api" }
frontend = { path = "../lib/frontend" }
config = { path = "../lib/config" }
localization = { path = "../lib/localization" }
resources = { path = "../lib/resources" }
actix-files = "0.6.0"
actix-web = "4.0.1"
actix-multipart = "0.4.0"
argparse = "0.2.2"
env_logger = "0.9.0"
serde = "1.0.137"
log = "0.4.17"
sentry = { version = "0.25.0", optional = true }
rayon = "1.5.2"
snmalloc-rs = "0.2.28"

[features]
sentry_error = [ "sentry", "frontend/sentry_error" ]
img_scan = [ "api/img_scan" ]
default = [ "img_scan","news_inotify" ]
news_inotify = [ "resources/news_inotify"]

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "my_benchmark"
harness = false
